import { CheckCircle2, Clock3, ShieldAlert, ShieldCheck, Box, FileText, Link2, Copy } from "lucide-react";
import type { BlockchainProof, IntegrityStatus, Submission } from "@/types/domain";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
export function Logo({compact=false}:{compact?:boolean}){return <div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md border border-primary/30 bg-primary/10 text-primary"><Box className="size-5"/></span>{!compact&&<div><strong className="text-sm tracking-[.14em]">BLOCKSUBMIT</strong><p className="text-[10px] text-muted-foreground">ACADEMIC INTEGRITY</p></div>}</div>}
export function StatusBadge({status}:{status:IntegrityStatus}){const s={VERIFIED:"border-success/25 bg-success/10 text-success",PENDING:"border-warning/25 bg-warning/10 text-warning",TAMPERED:"border-destructive/25 bg-destructive/10 text-destructive"}[status];const Icon=status==="VERIFIED"?CheckCircle2:status==="PENDING"?Clock3:ShieldAlert;return <span className={cn("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-bold",s)}><Icon className="size-3.5"/>{status}</span>}
export function MetricCard({label,value,icon:Icon,tone="primary"}:{label:string;value:number|string;icon:any;tone?:"primary"|"success"|"warning"|"danger"}){const tones={primary:"bg-primary/10 text-primary",success:"bg-success/10 text-success",warning:"bg-warning/10 text-warning",danger:"bg-destructive/10 text-destructive"};return <article className="panel animate-rise rounded-lg p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div><span className={cn("grid size-9 place-items-center rounded-md",tones[tone])}><Icon className="size-4"/></span></div></article>}
export function EmptyState({title,detail}:{title:string;detail:string}){return <div className="panel rounded-lg px-6 py-14 text-center"><FileText className="mx-auto size-7 text-muted-foreground"/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div>}
const short=(v:string|null)=>v?`${v.slice(0,10)}…${v.slice(-8)}`:"Not available";
export function ProofPanel({proof}:{proof:BlockchainProof|null}){return <section className="panel rounded-lg p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold text-primary">BLOCKCHAIN PROOF</p><h3 className="mt-1 font-semibold">Immutable submission record</h3></div><Link2 className="size-5 text-primary"/></div><dl className="grid gap-4 sm:grid-cols-3"><Info label="Transaction" value={short(proof?.transactionHash??null)} mono/><Info label="Block" value={proof?.blockNumber?`#${proof.blockNumber}`:"Not available"}/><Info label="Status" value={proof?.status??"Not available"}/></dl></section>}
export function Info({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div><dt className="text-[11px] font-bold text-muted-foreground">{label.toUpperCase()}</dt><dd className={cn("mt-1 break-all text-sm",mono&&"font-mono text-xs text-primary")}>{value}</dd></div>}
export function HashComparison({submission}:{submission:Submission}){return <section className="panel rounded-lg p-5"><div className="mb-5 flex items-center gap-3"><ShieldCheck className="size-5 text-primary"/><div><p className="text-xs font-bold text-primary">INTEGRITY COMPARISON</p><h3 className="font-semibold">Document fingerprints</h3></div></div><div className="grid gap-4 lg:grid-cols-[1fr_auto_1fr]"><Hash label="Trusted hash" value={submission.trustedHash}/><div className="hidden items-center lg:flex"><span className={cn("rounded-full border px-3 py-1 text-xs font-bold",submission.hashMatch===true?"border-success/25 bg-success/10 text-success":submission.hashMatch===false?"border-destructive/25 bg-destructive/10 text-destructive":"border-border text-muted-foreground")}>{submission.hashMatch===null?"NOT CHECKED":submission.hashMatch?"MATCH":"MISMATCH"}</span></div><Hash label="Current hash" value={submission.currentHash}/></div></section>}
function Hash({label,value}:{label:string;value:string|null}){return <div className="rounded-md border bg-background/40 p-4"><p className="text-[11px] font-bold text-muted-foreground">{label.toUpperCase()}</p><p className="mt-2 break-all font-mono text-xs leading-5 text-foreground">{value??"Not available"}</p></div>}
export function PageHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow&&<p className="mb-2 text-xs font-bold text-primary">{eyebrow}</p>}<h1 className="text-2xl font-semibold sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{action}</header>}
export function CopyButton({value}:{value:string|null}){return <Button variant="ghost" size="icon" disabled={!value} aria-label="Copy value" onClick={()=>value&&navigator.clipboard.writeText(value)}><Copy/></Button>}
