import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Activity, AlertTriangle, BookOpen, CheckCircle2, Clock3, FileCheck2, ShieldCheck, UploadCloud } from "lucide-react";
import { assignmentService, activityService, submissionService } from "@/services";
import type { Activity as ActivityType, Assignment, Submission } from "@/types/domain";
import { MetricCard, PageHeading, StatusBadge } from "@/components/blocksubmit/shared";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { format, formatDistanceToNow } from "date-fns";
export function ProfessorDashboard(){const [data,setData]=useState<{a:Assignment[];s:Submission[];v:ActivityType[]}|null>(null);useEffect(()=>{Promise.all([assignmentService.list(),submissionService.list("professor"),activityService.list()]).then(([a,s,v])=>setData({a,s,v}))},[]);if(!data)return <DashboardSkeleton/>;const stats={totalAssignments:data.a.length,activeAssignments:data.a.filter(x=>x.status==="ACTIVE").length,totalSubmissions:data.s.length,verified:data.s.filter(x=>x.status==="VERIFIED").length,pending:data.s.filter(x=>x.status==="PENDING").length,tampered:data.s.filter(x=>x.status==="TAMPERED").length};return <div className="space-y-7"><PageHeading eyebrow="ACADEMIC INTEGRITY COMMAND CENTER" title="Good afternoon, Professor" description="Monitor submissions, verify document integrity, and review immutable proof records."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="TOTAL ASSIGNMENTS" value={stats.totalAssignments} icon={BookOpen}/><MetricCard label="ACTIVE" value={stats.activeAssignments} icon={Clock3}/><MetricCard label="SUBMISSIONS" value={stats.totalSubmissions} icon={FileCheck2}/><MetricCard label="VERIFIED" value={stats.verified} icon={CheckCircle2} tone="success"/><MetricCard label="PENDING" value={stats.pending} icon={Clock3} tone="warning"/><MetricCard label="TAMPERED" value={stats.tampered} icon={AlertTriangle} tone="danger"/></div><div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><RecentSubmissions items={data.s}/><ActivityList items={data.v}/></div></div>}
export function StudentDashboard(){const [data,setData]=useState<{a:Assignment[];s:Submission[]}|null>(null);useEffect(()=>{Promise.all([assignmentService.list(),submissionService.list("student")]).then(([a,s])=>setData({a,s}))},[]);if(!data)return <DashboardSkeleton/>;const active=data.a.filter(x=>x.status==="ACTIVE");return <div className="space-y-7"><PageHeading eyebrow="SECURE SUBMISSION WORKSPACE" title="Welcome back, Aarav" description="Track your assignments and keep every document's integrity proof in one place."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="ACTIVE ASSIGNMENTS" value={active.length} icon={BookOpen}/><MetricCard label="PENDING SUBMISSIONS" value={data.s.filter(x=>x.status==="PENDING").length} icon={Clock3} tone="warning"/><MetricCard label="COMPLETED" value={data.s.length} icon={FileCheck2}/><MetricCard label="VERIFIED" value={data.s.filter(x=>x.status==="VERIFIED").length} icon={ShieldCheck} tone="success"/></div><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Upcoming assignments</h2><p className="text-sm text-muted-foreground">Prioritized by deadline</p></div><Link to="/student/assignments" className="text-sm font-semibold text-primary">View all</Link></div><div className="space-y-3">{active.map(a=><article key={a.id} className="panel rounded-lg p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className="text-xs font-bold text-primary">{a.code}</span><span className="text-xs text-muted-foreground">Due {format(new Date(a.deadline),"MMM d, h:mm a")}</span></div><h3 className="mt-2 font-semibold">{a.title}</h3><p className="mt-1 text-sm text-muted-foreground">{a.description}</p></div><Button asChild variant={a.submissionStatus==="NOT_SUBMITTED"?"default":"outline"}><Link to="/student/assignments/$id" params={{id:a.id}}>{a.submissionStatus==="NOT_SUBMITTED"?<><UploadCloud/>Submit</>:"View"}</Link></Button></div></article>)}</div></section><RecentSubmissions items={data.s} student/></div></div>}
function RecentSubmissions({items,student=false}:{items:Submission[];student?:boolean}){return <section className="panel overflow-hidden rounded-lg"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">{student?"Recent submissions":"Recent submissions"}</h2><p className="text-sm text-muted-foreground">Latest document records</p></div><Link to={student?"/student/submissions":"/professor/submissions"} className="text-sm font-semibold text-primary">View all</Link></div><div className="divide-y">{items.slice(0,5).map(s=><Link key={s.id} to={student?"/student/submissions/$id":"/professor/submissions/$id"} params={{id:s.id}} className="flex items-center gap-3 p-4 transition-colors hover:bg-accent/50"><span className="grid size-9 shrink-0 place-items-center rounded-md bg-secondary"><FileCheck2 className="size-4 text-primary"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{student?s.assignmentTitle:s.student.name}</p><p className="truncate text-xs text-muted-foreground">{s.documentName}</p></div><div className="hidden text-right md:block"><StatusBadge status={s.status}/><p className="mt-1 text-[11px] text-muted-foreground">{formatDistanceToNow(new Date(s.submittedAt),{addSuffix:true})}</p></div></Link>)}</div></section>}
export function ActivityList({items}:{items:ActivityType[]}){return <section className="panel rounded-lg p-5"><div className="mb-5"><h2 className="font-semibold">Integrity activity</h2><p className="text-sm text-muted-foreground">Recent system events</p></div><div className="relative space-y-5 before:absolute before:bottom-2 before:left-[15px] before:top-2 before:w-px before:bg-border">{items.map(e=><div key={e.id} className="relative flex gap-3"><span className="z-10 grid size-8 shrink-0 place-items-center rounded-full border bg-card"><Activity className="size-3.5 text-primary"/></span><div><p className="text-sm font-semibold">{e.title}</p><p className="text-xs text-muted-foreground">{e.detail}</p><p className="mt-1 text-[11px] text-muted-foreground">{formatDistanceToNow(new Date(e.timestamp),{addSuffix:true})}</p></div></div>)}</div></section>}
function DashboardSkeleton(){return <div className="space-y-7"><Skeleton className="h-20 w-full"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(x=><Skeleton key={x} className="h-32"/>)}</div><Skeleton className="h-96"/></div>}
